### ISSUE TITLE
I get an error of undefined after selecting a json file?

### ISSUE THREAD

**Issue by Nuclear6** [adobe-research/VideoDoodles#3]
![image](https://github.com/user-attachments/assets/d4b0f923-c0f4-45e6-bc21-12affa91962d)

**Comment by SongOnWater** [comment]
[preprocessing](https://github.com/adobe-research/VideoDoodles/blob/main/preprocess) 文档中说把他们提供的frontend 和 backend 样例解压缩到相应文件夹下，但只能操作他们提供的样例。

**Comment by em-yu** [comment]
Hi, indeed please sure that you have extracted the [backend data files](https://repo-sam.inria.fr/d3/VideoDoodles/video-doodles-preprocessed-data-backend.zip) in `VideoDoodles/app/backend/data`, such that you have the following folder structure:
```
VideoDoodles/app/backend
    data
        blackswan
        car-roundabout
        ...
        train
```

**Comment by Nuclear6** [comment]
I have placed the corresponding files in the specified directory, but I did not use docker to start. I split them into local startups according to the docker file. Do I have to use docker to start?

**Comment by Nuclear6** [comment]
There is something wrong with my decompression method, thanks @em-yu

<img width="1027" alt="image" src="https://github.com/user-attachments/assets/068361d7-1f64-4f54-b7f8-2b19240c5ee8">
