### ISSUE TITLE
How to get "input data" for "preprocessing "

### ISSUE THREAD

**Issue by SongOnWater** [adobe-research/VideoDoodles#4]
In the document of [preprocessing](https://github.com/adobe-research/VideoDoodles/blob/main/preprocess) part, the processing needs raw input data one folder per video, which contains 5 files : frames.npz  flows.npz flows_con.npz resized_disps.npz  refined_cameras.txt . But how could I get the 5 files from a video file? 
Thanks.

**Comment by em-yu** [comment]
Hi, please see my reply [here](https://github.com/adobe-research/VideoDoodles/issues/1)
